###############################################################
author: Jaime_A_Castro_Mondragon
author2: Robin_van_der_Lee

###############################
## Expected folder structure ##
###############################
## The Snakefile will launch a motif analysis + calculate centrality for each discovered motifs for every set of peaks in Narrowpeak format found in the 'data_folder'.
##
## Example:
##
## cd data_folder
##
## .
## ├── ERX032305_S2_Lint-1
## │   └── ERX032305_S2_Lint-1_peaks.narrowPeak
## └── ERX032306_Kc_Lint-1
##     └── ERX032306_Kc_Lint-1_peaks.narrowPeak
##
## Every EXPERIMENT_FOLDER in the data folder must contain a narrowPeak file with the same name, see tree above.
## This is the data structure required by the pipeline.


## === ##
## Bin ##
## === ##
bin : /home/rvdlee/JASPAR/jaimicore-jaspar_2020-a8db6feb9e0e/motif_discovery_pipeline/bin
python : python2.7
RSAT : /sp1work/Tools/rsat


## ============================================= ##
## Motif discovery (RSAT peak-motifs) parameters ##
## ============================================= ##
peakmotifs_disco : oligos,dyads,positions,local_words
peakmotifs_disco_nb_motifs : 2
peakmotifs_disco_min_oligo : 6
peakmotifs_disco_max_oligo : 7
peakmotifs_class_interval : 25

central_pvalue : -200


## ============================================ ##
## ModERN fly: folders and required input files ##
## ============================================ ##
data_folder : /home/rvdlee/JASPAR/ModERN/data/ModERN_fly_peaks_DATA
TF_Experiment_map : /home/rvdlee/JASPAR/ModERN/data/ModERN_fly_experimentList_TFs_and_others.tab
genome_fasta : /home/rvdlee/GENOMES/dm6.fa 
genome_size : /home/rvdlee/GENOMES/dm6.chrom.sizes
out_dir : /home/rvdlee/JASPAR/ModERN/results_cluster/ModERN_fly/output
curation_dir : /home/rvdlee/JASPAR/ModERN/results_cluster/ModERN_fly/curation

