################################################################
author: Jaime_A_Castro_Mondragon
author2: Robin_van_der_Lee

###############################
## Expected folder structure ##
###############################
## The Snakefile will launch a motif analysis + calculate centrality for each discovered motifs for every set of peaks in Narrowpeak format found in the 'data_folder'.
##
## Example:
##
## cd data_folder
##
## .
## ├── ERX032305_S2_Lint-1
## │   └── ERX032305_S2_Lint-1_peaks.narrowPeak
## └── ERX032306_Kc_Lint-1
##     └── ERX032306_Kc_Lint-1_peaks.narrowPeak
##
## Every EXPERIMENT_FOLDER in the data folder must contain a narrowPeak file with the same name, see tree above.
## This is the data structure required by the pipeline.


## === ##
## Bin ##
## === ##
bin    : ../../bin
python : python2.7
RSAT   : /lsc/rsat


## ============================================= ##
## Motif discovery (RSAT peak-motifs) parameters ##
## ============================================= ##
peakmotifs_disco : oligos,dyads,positions,local_words
peakmotifs_disco_nb_motifs : 2
peakmotifs_disco_min_oligo : 6
peakmotifs_disco_max_oligo : 7
peakmotifs_class_interval : 25

central_pvalue : -200


## ============================================= ##
## Folders and required input files ##
## ============================================= ##
data_folder       : /storage/mathelierarea/processed/jamondra/Projects/JASPAR/JASPAR_2020/Correct_number_sites/JASPAR_2020/motif_discovery_pipeline/CistromeDB/data/DATA_FILES/mouse_factor
TF_Experiment_map : /storage/mathelierarea/processed/JASPAR_2020/jaspar_2020/motif_discovery_pipeline/CistromeDB/data/CistromeDB_mouse_experiment_map.txt
genome_fasta      : /storage/mathelierarea/raw/UCSC/mm10/mm10.fa
genome_size       : /storage/mathelierarea/raw/UCSC/mm10/mm10.chrom.sizes
out_dir           : /storage/mathelierarea/processed/jamondra/Projects/JASPAR/JASPAR_2020/Correct_number_sites/JASPAR_2020/motif_discovery_pipeline/CistromeDB/results/CistromeDB_mouse
curation_dir      : /storage/mathelierarea/processed/jamondra/Projects/JASPAR/JASPAR_2020/Correct_number_sites/JASPAR_2020/motif_discovery_pipeline/CistromeDB/results/CistromeDB_mouse/curation
