################################################################
author: Jaime_A_Castro_Mondragon

###############################
## Expected folder structure ##
###############################
## The Snakefile will launch a motif analysis + calculate centrality for each discovered motifs for every set of peaks in Narrowpeak format found in the 'data_folder'.
##
## Example:
##
## cd data_folder
##
## .
## ├── ERX032305_S2_Lint-1
## │   └── ERX032305_S2_Lint-1_peaks.narrowPeak
## └── ERX032306_Kc_Lint-1
##     └── ERX032306_Kc_Lint-1_peaks.narrowPeak
##
## Every EXPERIMENT_FOLDER in the data folder must contain a narrowPeak file with the same name, see tree above.
## This is the data structure required by the pipeline.


## === ##
## Bin ##
## === ##
bin : ../bin
python : python2.7
RSAT : /lsc/rsat


## ============================================= ##
## Motif discovery (RSAT peak-motifs) parameters ##
## ============================================= ##
peakmotifs_disco : oligos,dyads,positions,local_words
peakmotifs_disco_nb_motifs : 2
peakmotifs_disco_min_oligo : 6
peakmotifs_disco_max_oligo : 7
peakmotifs_class_interval : 25


central_pvalue : -200


## ====================================================================== ##
## Schizosaccharomyces_pombe (ASM294v2): folders and required input files ##
## ====================================================================== ##
data_folder : /storage/scratch/JASPAR_2020/jaspar_2020/motif_discovery_pipeline/GTRD/data/peaks/Schizosaccharomyces_pombe
genome_fasta : /storage/scratch/JASPAR_2020/jaspar_2020/motif_discovery_pipeline/GTRD/data/genomes/ASM294v2/ASM294v2.fa
genome_size : /storage/scratch/JASPAR_2020/jaspar_2020/motif_discovery_pipeline/GTRD/data/genomes/ASM294v2/ASM294v2.chrom.sizes
TF_Experiment_map : /storage/scratch/JASPAR_2020/jaspar_2020/motif_discovery_pipeline/GTRD/data/experiment_table/Schizosaccharomyces_pombe/Schizosaccharomyces_pombe_GTRD_experiment_table.tab
out_dir : GTRD_results/Schizosaccharomyces_pombe_ASM294v2
curation_dir : GTRD_results/curation/Schizosaccharomyces_pombe_ASM294v2